[package]
name = "slack-anonymizer"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.40", features = ["derive"] }
regex = "1.11.1"
serde = "1.0.219"
thiserror = "2.0.12"
rand = "0.8"

[dev-dependencies]
tempfile = "3.8"
